### ISSUE TITLE
High memory load with scikit-learn (without parallelization)

### ISSUE THREAD

**Issue by gprinz** [tarrade/proj_NLP_text_classification_with_GCP#39]

**Comment by gprinz** [comment]
Machine: n2-highmem-8
Dataset size: about 400 MB

**Memory Load Statistics (Fabien's Pipeline)**
- Before the training: about 0.5%
- During the training: about 60%
- After the training: about 8.5%

-> problem persists if the pipeline's parameter are adapted.
-> the memory increases with every run by 5% (i.e. there seems to be a problem in the memory handling).

![image](https://user-images.githubusercontent.com/32190139/70317717-9a989d80-181e-11ea-98bb-883edb32fc7a.png)

**Comment by tarrade** [comment]
Cool, this is what I obserbed (40%). I guess if you start the VM, I will guess some memry will be clean and it should go down to 0
On my side:
- I don't see memory issue if I don't use pipeline !
- I did an updat to scikit-learn 0.22 and I need to redo all tests
- I am repacking mem and cpu function so it is more easy to switch
- I will switch to the subset dataset
- I will need to retests everything with this ned setup to compare apple with apple

**Comment by gprinz** [comment]
You are right, but the memory should also be release without restarting the VM. What I found out further:

- Newest version if scikit-learn (v. 0.22) does not solve the problem.
- I observe problems when working with a pipeline

Further steps: Double check the results and report the issues to the creators of scikit-learn

**Comment by tarrade** [comment]
Locally with scikit-learn 0.22:
- the bug issue is related to label
- it could be that we have memory leak in scikit-learn 0.22 [not investigated]
- it could be that we have memory leak with pipeline scikit-learn 0.22 [not investigated]

The issue is the following:
- we pass for training, a df columns with the labe; : [c, c++, java ...]
- the training will transform this in 1-hot encoded matrxi
- the issue that we have too many labels [see the other ticket]
- the training function will start by creating a numpy array with zero n_rwo x n_labels as simulated below

```
import numpy as np
row=1
feature=15000
test=np.zeros((row,feature), dtype=int)
total_row=31e6
print('memory needed for {:,} entries and {:,} features: {:.2f} Gb'.format(total_row,feature,(total_row*test.nbytes/1024**3)/row))
```
memory needed for 31,000,000.0 entries and 15,000 features: 3464.52 Gb

so we need 3.6 TB of memory to store a hot=encoding vector for 31M rows and 15' 000 features

I think this is the main issue.

For these tests, I did the following which was created "new" labels
if we have the following label vector: 
[ ['c'], ['c++'], ['java','c']] 
i transormed it in the following way:
['c', 'c++', 'java,c']
which means that we have new label corresponding to multiple labels together.

I have a new code to do label selection in a proper way and we can also defined a maximum number of label. I also limit the vocabulary size to 10'000 (hard coded).

I consider this issue fixed but in case of other issue, please reopen (memory leak, pipeline ...)

With the new code, I can now run much more data.

**Comment by tarrade** [comment]
8h to train a model on 2.5M events. No memory issue anymore. I guess I see now the correct total number of labels: 50
